server:
 servlet:
    context-path: /cliente-pet-servico/api
    
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: ${MONGO_DB_URI:mongodb+srv://ana:140665@cluster0.a323abq.mongodb.net/Cluster0?retryWrites=true&w=majority}
      auto-index-creation: true    
      
springdoc:
  swagger-ui:
    path: /public/swagger