server:
 servlet:
    context-path: /cliente-pet-servico/api
    
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: 123
    password: 123
    driverClassName: org.h2.Driver
     
  h2:
    console:
      enabled: true
      path: /h2-console